## Import

In [1]:
from PublicDataReader import Ecos

import xlwings as xw
import pandas as pd
import numpy as np
import time

* api setting

In [2]:
KEY = 'GG5O3Y75NZ9O6CN5QCBW'

In [3]:
## 통계 테이블
api = Ecos(KEY)
meta = api.get_statistic_table_list()
meta = meta.loc[meta['검색가능여부'] == 'Y']
meta.index = [x for x in range(meta.shape[0])]

In [9]:
def check_code(meta, key):
    return meta.loc[meta['통계명'] == key]['통계표코드'].values[0]

In [16]:
code = check_code(meta, '8.4.5. 미분양주택현황')
df = api.get_statistic_item_list(통계표코드=code); df.head(15)

,통계표코드,통계명,항목그룹코드,항목그룹명,통계항목코드,통계항목명,상위통계항목코드,상위통계항목명,시점,수록시작일자,수록종료일자,자료수,단위,가중치
0,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410A,전국,None,None,A,2001,2022,22,호,None
1,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410A,전국,None,None,M,200701,202309,201,호,None
2,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410B,서울,None,None,A,2001,2022,22,호,None
3,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410B,서울,None,None,M,200701,202309,201,호,None
4,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410C,부산,None,None,A,2001,2022,22,호,None
5,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410C,부산,None,None,M,200701,202309,201,호,None
6,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410D,대구,None,None,A,2001,2022,22,호,None
7,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410D,대구,None,None,M,200701,202309,201,호,None
8,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410E,인천,None,None,A,2001,2022,22,호,None
9,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410E,인천,None,None,M,200701,202309,201,호,None
10,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410F,광주,None,None,A,2001,2022,22,호,None
11,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410F,광주,None,None,M,200701,202309,201,호,None
12,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410G,대전,None,None,A,2001,2022,22,호,None
13,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410G,대전,None,None,M,200701,202309,201,호,None
14,901Y074,8.4.5. 미분양주택현황,Group1,계정항목,I410H,울산,None,None,A,2001,2022,22,호,None

In [15]:
# 전국
df = api.get_statistic_search(통계표코드=code, 통계항목코드1 = 'I410A', 주기="M", 검색시작일자="202001", 검색종료일자="202311")
df.tail()

,통계표코드,통계명,통계항목코드1,통계항목명1,통계항목코드2,통계항목명2,통계항목코드3,통계항목명3,통계항목코드4,통계항목명4,단위,시점,값
40,901Y074,8.4.5. 미분양주택현황,I410A,전국,None,None,None,None,None,None,호,202305,68865
41,901Y074,8.4.5. 미분양주택현황,I410A,전국,None,None,None,None,None,None,호,202306,66388
42,901Y074,8.4.5. 미분양주택현황,I410A,전국,None,None,None,None,None,None,호,202307,63087
43,901Y074,8.4.5. 미분양주택현황,I410A,전국,None,None,None,None,None,None,호,202308,61811
44,901Y074,8.4.5. 미분양주택현황,I410A,전국,None,None,None,None,None,None,호,202309,59806

In [14]:
# 서울
df = api.get_statistic_search(통계표코드=code, 통계항목코드1 = 'I410B', 주기="M", 검색시작일자="202001", 검색종료일자="202311")
df.tail()

,통계표코드,통계명,통계항목코드1,통계항목명1,통계항목코드2,통계항목명2,통계항목코드3,통계항목명3,통계항목코드4,통계항목명4,단위,시점,값
40,901Y074,8.4.5. 미분양주택현황,I410B,서울,None,None,None,None,None,None,호,202305,1144
41,901Y074,8.4.5. 미분양주택현황,I410B,서울,None,None,None,None,None,None,호,202306,1181
42,901Y074,8.4.5. 미분양주택현황,I410B,서울,None,None,None,None,None,None,호,202307,1081
43,901Y074,8.4.5. 미분양주택현황,I410B,서울,None,None,None,None,None,None,호,202308,976
44,901Y074,8.4.5. 미분양주택현황,I410B,서울,None,None,None,None,None,None,호,202309,914

In [20]:
code = check_code(meta, '8.4.6. 주택건설인허가실적')
df = api.get_statistic_item_list(통계표코드=code); df

# 전국
df = api.get_statistic_search(통계표코드=code, 통계항목코드1 = 'ALL', 주기="M", 검색시작일자="202001", 검색종료일자="202311")
df.tail()

,통계표코드,통계명,통계항목코드1,통계항목명1,통계항목코드2,통계항목명2,통계항목코드3,통계항목명3,통계항목코드4,통계항목명4,단위,시점,값
40,901Y105,8.4.6. 주택건설인허가실적,ALL,전국,None,None,None,None,None,None,호,202305,157534
41,901Y105,8.4.6. 주택건설인허가실적,ALL,전국,None,None,None,None,None,None,호,202306,189213
42,901Y105,8.4.6. 주택건설인허가실적,ALL,전국,None,None,None,None,None,None,호,202307,207278
43,901Y105,8.4.6. 주택건설인허가실적,ALL,전국,None,None,None,None,None,None,호,202308,212757
44,901Y105,8.4.6. 주택건설인허가실적,ALL,전국,None,None,None,None,None,None,호,202309,255871

In [21]:
# 서울
df = api.get_statistic_search(통계표코드=code, 통계항목코드1 = 'SEO', 주기="M", 검색시작일자="202001", 검색종료일자="202311")
df.tail()

,통계표코드,통계명,통계항목코드1,통계항목명1,통계항목코드2,통계항목명2,통계항목코드3,통계항목명3,통계항목코드4,통계항목명4,단위,시점,값
40,901Y105,8.4.6. 주택건설인허가실적,SEO,서울,None,None,None,None,None,None,호,202305,16361
41,901Y105,8.4.6. 주택건설인허가실적,SEO,서울,None,None,None,None,None,None,호,202306,17589
42,901Y105,8.4.6. 주택건설인허가실적,SEO,서울,None,None,None,None,None,None,호,202307,18536
43,901Y105,8.4.6. 주택건설인허가실적,SEO,서울,None,None,None,None,None,None,호,202308,19370
44,901Y105,8.4.6. 주택건설인허가실적,SEO,서울,None,None,None,None,None,None,호,202309,19778

In [26]:
code = check_code(meta, '4.4.1.1. 주택매매가격지수(KB)')
df = api.get_statistic_item_list(통계표코드=code); df

,통계표코드,통계명,항목그룹코드,항목그룹명,통계항목코드,통계항목명,상위통계항목코드,상위통계항목명,시점,수록시작일자,수록종료일자,자료수,단위,가중치
0,901Y062,4.4.1.1. 주택매매가격지수(KB),Group1,계정항목,P63ACA,아파트(서울),P63AC,아파트,M,198601,202310,454,2022.01=100,None
1,901Y062,4.4.1.1. 주택매매가격지수(KB),Group1,계정항목,P63A,총지수,None,None,M,198601,202310,454,2022.01=100,None
2,901Y062,4.4.1.1. 주택매매가격지수(KB),Group1,계정항목,P63AA,단독주택,P63A,총지수,M,198601,202310,454,2022.01=100,None
3,901Y062,4.4.1.1. 주택매매가격지수(KB),Group1,계정항목,P63AB,연립주택,P63A,총지수,M,198601,202310,454,2022.01=100,None
4,901Y062,4.4.1.1. 주택매매가격지수(KB),Group1,계정항목,P63AC,아파트,P63A,총지수,M,198601,202310,454,2022.01=100,None
5,901Y062,4.4.1.1. 주택매매가격지수(KB),Group1,계정항목,P63AD,총지수(서울),P63A,총지수,M,198601,202310,454,2022.01=100,None

In [29]:
code = check_code(meta, '4.4.3.1. 유형별 주택매매가격지수')
df = api.get_statistic_item_list(통계표코드=code); df

,통계표코드,통계명,항목그룹코드,항목그룹명,통계항목코드,통계항목명,상위통계항목코드,상위통계항목명,시점,수록시작일자,수록종료일자,자료수,단위,가중치
0,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group1,구분코드,H69A,종합,None,None,M,200311,202309,5628,None,None
1,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group1,구분코드,H69B,아파트,None,None,M,200311,202309,5628,None,None
2,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group1,구분코드,H69C,연립다세대,None,None,M,200311,202309,5628,None,None
3,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group1,구분코드,H69D,단독주택,None,None,M,200311,202309,5628,None,None
4,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70A,전국,None,None,M,200311,202309,956,2021.6=100,None
5,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70B,수도권,None,None,M,200311,202309,956,2021.6=100,None
6,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70C,지방,None,None,M,200311,202309,956,2021.6=100,None
7,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70D,5대광역시,None,None,M,200311,202309,956,2021.6=100,None
8,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70E,8개도,None,None,M,200311,202309,956,2021.6=100,None
9,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70F,서울,None,None,M,200311,202309,956,2021.6=100,None
10,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70G,경기,None,None,M,200311,202309,956,2021.6=100,None
11,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70H,인천,None,None,M,200311,202309,956,2021.6=100,None
12,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70I,부산,None,None,M,200311,202309,956,2021.6=100,None
13,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70J,대구,None,None,M,200311,202309,956,2021.6=100,None
14,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70K,광주,None,None,M,200311,202309,956,2021.6=100,None
15,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70L,대전,None,None,M,200311,202309,956,2021.6=100,None
16,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70M,울산,None,None,M,200311,202309,956,2021.6=100,None
17,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70N,세종,None,None,M,201211,202309,524,2021.6=100,None
18,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70O,강원,None,None,M,200311,202309,956,2021.6=100,None
19,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70P,충북,None,None,M,200311,202309,956,2021.6=100,None
20,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70Q,충남,None,None,M,200311,202309,956,2021.6=100,None
21,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70R,전북,None,None,M,200311,202309,956,2021.6=100,None
22,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70S,전남,None,None,M,200311,202309,956,2021.6=100,None
23,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70T,경북,None,None,M,200311,202309,956,2021.6=100,None
24,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70U,경남,None,None,M,200311,202309,956,2021.6=100,None
25,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70V,제주,None,None,M,200311,202309,956,2021.6=100,None
26,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70W,6대광역시,None,None,M,200311,202309,956,2021.6=100,None
27,901Y093,4.4.3.1. 유형별 주택매매가격지수,Group2,계정항목,R70X,9개도,None,None,M,200311,202309,956,2021.6=100,None

In [39]:
# 전국
df = api.get_statistic_search(통계표코드=code, 통계항목코드1 = 'H69A', 주기="M", 검색시작일자="202301", 검색종료일자="202309")
df.tail()

,통계표코드,통계명,통계항목코드1,통계항목명1,통계항목코드2,통계항목명2,통계항목코드3,통계항목명3,통계항목코드4,통계항목명4,단위,시점,값
211,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70T,경북,None,None,None,None,2021.6=100,202309,100.3
212,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70U,경남,None,None,None,None,2021.6=100,202309,97.5
213,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70V,제주,None,None,None,None,2021.6=100,202309,101.6
214,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70W,6대광역시,None,None,None,None,2021.6=100,202309,92.8
215,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70X,9개도,None,None,None,None,2021.6=100,202309,97.7

In [40]:
df

,통계표코드,통계명,통계항목코드1,통계항목명1,통계항목코드2,통계항목명2,통계항목코드3,통계항목명3,통계항목코드4,통계항목명4,단위,시점,값
0,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70A,전국,None,None,None,None,2021.6=100,202301,98.2
1,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70B,수도권,None,None,None,None,2021.6=100,202301,97.3
2,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70C,지방,None,None,None,None,2021.6=100,202301,99
3,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70D,5대광역시,None,None,None,None,2021.6=100,202301,96
4,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70E,8개도,None,None,None,None,2021.6=100,202301,101.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70T,경북,None,None,None,None,2021.6=100,202309,100.3
212,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70U,경남,None,None,None,None,2021.6=100,202309,97.5
213,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70V,제주,None,None,None,None,2021.6=100,202309,101.6
214,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70W,6대광역시,None,None,None,None,2021.6=100,202309,92.8
215,901Y093,4.4.3.1. 유형별 주택매매가격지수,H69A,종합,R70X,9개도,None,None,None,None,2021.6=100,202309,97.7

In [45]:
key = '2.4.10. 주택 시가총액(명목, 연말기준)'

In [46]:
code = check_code(meta, key)
df = api.get_statistic_item_list(통계표코드=code); df

,통계표코드,통계명,항목그룹코드,항목그룹명,통계항목코드,통계항목명,상위통계항목코드,상위통계항목명,시점,수록시작일자,수록종료일자,자료수,단위,가중치
0,291Y424,"2.4.10. 주택 시가총액(명목, 연말기준)",Group1,계정항목,101,주택 시가총액,None,None,A,1995,2022,28,십억원,None

In [42]:
[x for x in meta.통계명 if '주택' in x]

['2.4.10. 주택 시가총액(명목, 연말기준)',
 '4.4.1.1. 주택매매가격지수(KB)',
 '4.4.1.2. 주택전세가격지수(KB)',
 '4.4.3.1. 유형별 주택매매가격지수',
 '4.4.3.2. 유형별 주택전세가격지수',
 '4.4.3.3. 유형별 주택월세통합가격지수',
 '8.4.5. 미분양주택현황',
 '8.4.6. 주택건설인허가실적',
 '8.4.7. 주택보유수/주택보급률',
 '8.7.1.2. 주택종류별 자산, 부채, 소득 현황(2017~)',
 '8.7.2.2. 주택종류별 자산, 부채, 소득 현황(2012~2017)']